Day3/auction_site2/config/routes.rb
Rails.application.routes.draw do

get "/" => "products#index"

  resources :users do
    resources :products
  end

end

Day3/auction_site2/app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :user
	has_many :bids
	
end

Day3/auction_site2/app/models/user.rb
class User < ActiveRecord::Base
	has_many :products
end

Day3/auction_site2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Day3/auction_site2/app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.all
		@users = User.all
	end

	def show
		
	end

	def create
		
	end

	def destroy
		
	end
end

Day3/auction_site2/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		
	end

	def create
		
	end

	def destroy
		
	end

	def new
		
	end
end

Day3/auction_site2/app/helpers/application_helper.rb
module ApplicationHelper
end

Day3/auction_site2/app/helpers/products_helper.rb
module ProductsHelper
end

Day3/auction_site2/app/helpers/users_helper.rb
module UsersHelper
end

Day3/auction_site2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AuctionSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

Day3/auction_site2/app/views/products/index.html.erb
<h1>The Users</h1>

<% @users.each do |user| %>
	
	<li><%= link_to(user.name, user_products_path(user.id)) %></li>

<% end %>



<h1>The Products</h1>

<% @products.each do |product| %>
	
	<li><%= product.title %></li>

<% end %>